### ISSUE TITLE
NUM is a head of NP

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Polish-SZ#1]
in Polish UD 2.1

1	W	w	ADP	prep:loc:nwok	AdpType=Prep|Case=Loc|Variant=Short	2	case	_	_
2	pięciu	pięć	NUM	num:pl:loc:m3:congr	Animacy=Inan|Case=Loc|Gender=Masc|Number=Plur	6	obl:arg	_	_
3	sklepach	sklep	NOUN	subst:pl:loc:m3	Animacy=Inan|Case=Loc|Gender=Masc|Number=Plur	2	nmod	_	_
4	nic	nic	PRON	subst:sg:gen:n	Case=Gen|Gender=Neut|Number=Sing|PronType=Neg	6	obj	_	_
5	nie	nie	PART	qub	_	6	advmod	_	_
6	znaleziono	znaleziony	ADJ	imps:perf	Aspect=Perf|Case=Nom|Gender=Neut|Number=Sing|Polarity=Pos|VerbForm=Part|Voice=Pass	0	root	_	SpaceAfter=No

**Comment by dan-zeman** [comment]
Looks like a bug. Will look into it.

**Comment by dan-zeman** [comment]
Fixed in the dev branch.
