### ISSUE TITLE
Duplicate enhanced relation declaration

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_Polish-SZ#2]
In version 2.2, file `pl_lfg-ud-train.conllu`, line `110325`:

```
1	Przecież	przecież	PART	qub	_	6	advmod	6:advmod|8:advmod|10:advmod|12:advmod|12:advmod	_
```

The same enhanced relation `12:advmod` is defined twice.

**Comment by dan-zeman** [comment]
Thanks for reporting but if the bug occurs in `pl_lfg*.conllu`, then this is a wrong issue tracker, it should go to https://github.com/UniversalDependencies/UD_Polish-LFG/issues/.

**Comment by bguil** [comment]
You're right, I move it to the other tracker
